[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.20.0"
  SECRETS_SCAN_ENABLED = "false"

# Completely disable secrets scanning
[secrets_scan]
  enabled = false

# Headers for caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
